"""Implementation of Depth-First Search,Breadth-first search and A* search on a maze puzzle generated by prim_maze_generator


Hitarth Patel, Mohawk College, December 2024
"""
## import LifoQueue (stack)
from queue import LifoQueue, Queue, PriorityQueue

## import puzzle api
from maze_puzzle import get_start_state, is_goal, next_states, print_result_maze
from prim_maze_generator import generate_maze, print_maze

## import path.py
from path import create_path, print_path, add_state_to_path

## DFS solver
def DFS(maze):
    """Performs a depth-first search starting at start_state. Returns a tuple of path
    to indicate location of path to the goal. Relies on functions is_goal and
    next_states to define the goal and the search and uses stack to store potential
    paths"""

    start_state = get_start_state(maze)

    if not start_state:
        print("No valid start state found.")
        return None

    closed = []                 # init open, closed
    open = LifoQueue()
    open.put((0, start_state, create_path(start_state)))

    while not open.empty():        # loop until no more open states

        cost, state, path = open.get(False)    # get next state to expand

        if state not in closed:    # prune?

            closed.append(state)   # mark state visited (closed)

            if is_goal(state, maze):     # success?
                return path, cost

            for new_state in next_states(state, maze):    # expand state
                if maze[new_state[0]][new_state[1]] == 'c': new_cost = cost + 1
                else: new_cost = cost + 1 + int(maze[new_state[0]][new_state[1]])
                new_path = add_state_to_path(path, new_state)
                open.put((new_cost, new_state, new_path))                 # new states are open

    return None              # goal not found

## BFS solver
def BFS(maze):
    """Performs a Breadth-first search starting at start_state. Returns a tuple of path
    to indicate location of path to the goal. Relies on functions is_goal and
    next_states to define the goal and the search and uses queue to store potential
    paths"""

    start_state = get_start_state(maze)
    if not start_state:
        print("No valid start state found.")
        return None

    closed = []                 # init open, closed
    open = Queue()
    open.put((0, start_state, create_path(start_state)))

    while not open.empty():        # loop until no more open states

        cost, state, path = open.get(False)    # get next state to expand

        if state not in closed:    # prune?

            closed.append(state)   # mark state visited (closed)

            if is_goal(state, maze):     # success?
                return path, cost

            for new_state in next_states(state, maze):    # expand state
                if maze[new_state[0]][new_state[1]] == 'c': new_cost = cost + 1
                else: new_cost = cost + 1 + int(maze[new_state[0]][new_state[1]])
                new_path = add_state_to_path(path, new_state)
                open.put((new_cost, new_state, new_path))                 # new states are open

    return None              # goal not found

"""Resource: https://stackoverflow.com/questions/28666629/understanding-a-heuristics-for-single-goal-maze"""

def heuristic(state, maze):
    """
    Computes the Manhattan distance from the current state to the goal.
    """
    goal_row = len(maze) - 1  # Goal is in the last row
    goal_col = next((col for col in range(len(maze[0])) if maze[goal_row][col] == 'c'), None)
    row, col = state
    return abs(goal_row - row) + abs(goal_col - col)

## A* solver
def A(maze):
    """Performs a A* search starting at start_state. Returns a tuple of path
    to indicate location of path to the goal. Relies on functions is_goal and
    next_states and heuristic to define the goal and the search and uses Priority queue to store
    potential paths"""

    start_state = get_start_state(maze)
    if not start_state:
        print("No valid start state found.")
        return None

    closed = []                 # init open, closed
    open = PriorityQueue()
    open.put((0, 0, start_state, create_path(start_state)))

    while not open.empty():        # loop until no more open states

        heuristic_cost, cost, state, path = open.get(False)    # get next state to expand

        if state not in closed:    # prune?

            closed.append(state)   # mark state visited (closed)

            if is_goal(state, maze):     # success?
                return path, cost

            for new_state in next_states(state, maze):    # expand state
                if maze[new_state[0]][new_state[1]] == 'c':
                    new_cost = cost + 1
                else: new_cost = cost + 1 + int(maze[new_state[0]][new_state[1]])
                heuristic_cost = new_cost + heuristic(new_state, maze)
                new_path = add_state_to_path(path, new_state)
                open.put((heuristic_cost, new_cost, new_state, new_path))  # store (cost, state, path)

    return None              # goal not found

## run the solver
from time import time

# Generate a maze
print("******MAZE PUZZLE SOLVER******")

height, width = int(input("Enter heigth for puzzle: ")), int(input("Enter width for puzzle: "))
maze = generate_maze(height, width, multipath=True, diff_param=0.5)
print("MAZE : ",height," X ",width)
print_maze(maze)


# Solve the maze using DFS
start = time()
solution_path, cost = DFS(maze)
end = time()

if solution_path:
    print("\nDFS => Solution Found!")
    print("Path Length:", len(solution_path) - 1)
    print("Cost to Reach:", cost)
    print_result_maze(maze, solution_path)
else:
    print("\nNo solution found.")

print("DFS => Time:",end-start,"seconds")



# Solve the maze using BFS
start = time()
solution_path, cost = BFS(maze)
end = time()

if solution_path:
    print("\nBFS => Solution Found!")
    print("Path Length:", len(solution_path) - 1)
    print("Cost to Reach:", cost)
    print_result_maze(maze, solution_path)
else:
    print("\nNo solution found.")

print("BFS => Time:",end-start,"seconds")



# Solve the maze using A*
start = time()
solution_path, cost = A(maze)
end = time()

if solution_path:
    print("\nA* => Solution Found!")
    print("Path Length:", len(solution_path) - 1)
    print("Cost to Reach:", cost)
    print_result_maze(maze, solution_path)
else:
    print("\nNo solution found.")

print("A* => Time:",end-start,"seconds")